### ISSUE TITLE
Sketch crashes when exiting Full Screen (Mac OSX)

### ISSUE THREAD

**Issue by francescocretti** [Dreamo-Italy/Dreamo-engine-ProcessingIDE#18]
When running Dreamo on Mac in full screen mode application crashes when exiting (ESC button).

Error message:

`java.lang.IllegalStateException: Not on FX application thread; currentThread = JavaFX Application Thread
 at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
 at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
 at javafx.stage.Window.setShowing(Window.java:921)
 at javafx.stage.Window.hide(Window.java:947)
 at com.sun.javafx.stage.WindowPeerListener.closed(WindowPeerListener.java:100)
 at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:119)
 at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
 at java.security.AccessController.doPrivileged(Native Method)
 at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:151)
 at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
 at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:149)
 at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
 at com.sun.glass.ui.Window.notifyDestroy(Window.java:1183)
`

Probably an error with **FX2D** rendering engine

**Comment by francescocretti** [comment]
Related posts

- https://stackoverflow.com/questions/29449297/java-lang-illegalstateexception-not-on-fx-application-thread-currentthread-t'

- https://stackoverflow.com/questions/17850191/why-am-i-getting-java-lang-illegalstateexception-not-on-fx-application-thread

- https://stackoverflow.com/questions/21083945/how-to-avoid-not-on-fx-application-thread-currentthread-javafx-application-th
